spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/restarandb
spring.datasource.username=postgres
spring.datasource.password=husan_00$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=dGhpcy1pcy1hLXZlcnktc2VjdXJlLWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tdGhhdC1tdXN0LWJlLWF0LWxlYXN0LTI1Ni1iaXRz
jwt.expiration=86400000

# Telegram Configuration
telegram.bot.dining.token=8802101580:AAEYQ7p9eOLwkLDoTfk1zrY2SYUmg1fVK6Y
telegram.bot.delivery.token=8676555859:AAFzCdFN6SWm9wUInDkhTmjYyKg2BRRfP2w
telegram.admin.chatId=6028004749

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.restaurant=DEBUG
